refactor: Added vitest to project

diff --git a/.github/workflows/run-static-checks.yml b/.github/workflows/run-static-checks.yml
--- a/.github/workflows/run-static-checks.yml
+++ b/.github/workflows/run-static-checks.yml
@@ -8,11 +8,19 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
-          node-version: '18'
+          node-version: "18"
+
       - run: npm ci
+
       - name: Run Linter
         run: npm run lint
+
       - name: Run Typechecker
         # Run type check even if the previous linter step failed
         if: success() || failure()
         run: npm run typeCheck
+
+      - name: Run Tests
+        # Run test even if the previous step(s) failed
+        if: success() || failure()
+        run: npm run test
